services:

  telegram-bot:
    image: telegram-bot
    container_name: telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    stop_signal: SIGINT
    working_dir: /app
    volumes:
      - .env:/app/.env:ro
